### ISSUE TITLE
Weird Issue.

### ISSUE THREAD

**Issue by corytortoise** [Nustle/Nustle-PocketMine#1]
Hi, I tried testing out Nustle for my server. It seems to work just as intended, but while the plugin was loaded, my server seemed to freeze upon stopping the server. I thought it was just coincidence at first, but after I removed the plugin from my server and restarted the server, it stopped without any issues. I just downloaded the plugin a few mimutes before I made this issue. I run Ubuntu OS on a Dedicated server, if any of that helps. Also, I am using Genisys.

**Comment by XFuryMCPE** [comment]
This isn't a problem with the plugin, we are not able to reproduce this issue
